export enum TelegramState {
    IDLE = 'IDLE',
    AWAITING_LINK_CODE = 'AWAITING_LINK_CODE',
    CREATING_TICKET_TITLE = 'CREATING_TICKET_TITLE',
    CREATING_TICKET_DESCRIPTION = 'CREATING_TICKET_DESCRIPTION',
    CREATING_TICKET_CATEGORY = 'CREATING_TICKET_CATEGORY',
    CREATING_TICKET_PRIORITY = 'CREATING_TICKET_PRIORITY',
    CREATING_HARDWARE_DATE = 'CREATING_HARDWARE_DATE',
    CREATING_HARDWARE_TIME = 'CREATING_HARDWARE_TIME',
    REPLYING_TO_TICKET = 'REPLYING_TO_TICKET',
    CHAT_MODE = 'CHAT_MODE', // Continuous conversation with a ticket
    AWAITING_TICKET_SELECTION = 'AWAITING_TICKET_SELECTION', // Selecting ticket for chat
}
